### ISSUE TITLE
Refresh Slide (question)

### ISSUE THREAD

**Issue by boschkundendienst** [codimd/server#113]
Hi, first of all thank you for your great work. Besides the "normal" CodiMD features I am currently exploring the Slideshow features as well and I think I could replace my current digital signage solution with CodiMD/reveal.js.

I created a Slideshow using CodiMD, published it and pointed a full-screen browser to the published URL.

How can I force the browser to refresh the content when I changed the slideshow inside CodiMD, I mean instant updates like they happen with "normal" CodiMD content?

I don't know how exactly reveal.js is implemented in CodiMD but is there a way to use the reveal.js socket feature eg. to run slideshows simultaniously?
I know I could do that with reveal.js itself but hey, CodiMD is such a cool backend for doing it, why not?

In the future I could see CodiMD also becoming a great backend for a digital signage solution. One can use CodiMD to edit and host the digital signage content without the need for commercial reveal.js backends like slides.com

Thanks and keep this good work going!

Peter

**Comment by SISheogorath** [comment]
Hey, this seems to be a question that is not directly a bug or a feature request, you might want to open this kind of questions in [our Community forum](https://community.codimd.org) instead of the issue tracker.

But in order to answer your question: We don't support live updates on slides in Slide mode, as I for example would consider it weird, when the Presentation I start is not the one I finished.

But we have a preview mode in the editor view, which mimes (yes, not everything is 100% correct) the Slide mode in order to make it easier to edit things. You can check that out here: https://demo.codimd.org/slide-example?both (Create a new note and copy the content, then change it :))

**Comment by boschkundendienst** [comment]
Thanks for the feedback. I will take a look the the community forum. Also I think I can achieve my goal bei putting the Slide insght an iFrame that gets refreshed after some amount of time. But as I pointed out. If CodiMD would directly support that would be great!
