### ISSUE TITLE
awkward vertical spacing if bulleted list contains a blank line

### ISSUE THREAD

**Issue by bitinerant** [codimd/server#142]
A blank line in a list of bullets causes the entire list to be much more spaced out vertically. In a very long list, it is difficult to find the source of the problem, especially if you don't know that this can be caused by a blank line. The same happens for a checkbox list.

Steps to reproduce:

1. In 'Both' mode, create a simple 5-item bulleted list.
2. Add a blank line between the first two list items in the list while watching the right-hand view.

Screenshot:
![image](https://user-images.githubusercontent.com/786662/63077273-a4288d80-bf2f-11e9-8fcc-4e2ac42b6dc3.png)

**Comment by ccoenen** [comment]
This one is tricky, because it is not simply a bug. It's meant to be this way in case you put long things into list items.

A single list item may contain many paragraphs of text like this:

```md
some test text

* item one
* item two with a number  
  of lines included
  all belonging to item two

  even after a blank line
* item three

done.
```

which would render as 

---

some test text

* item one
* item two with a number  
  of lines included
  all belonging to item two

  even after a blank line
* item three

done.

--- 

In that case, the list items contain a paragraph `<p>` element, which create the extra margin.

**Comment by ccoenen** [comment]
I just noticed: the same happens here on github (see example above)

**Comment by ccoenen** [comment]
(another test, disregard this post)

```markdown
* a
* b

* c
```
---
* a
* b

* c
---

**Comment by SISheogorath** [comment]
This is by commonmark definition: https://spec.commonmark.org/0.29/#example-284

**Comment by bitinerant** [comment]
@SISheogorath and @ccoenen - It's encouraging to see your responses and willingness to look into this issue. It still think it's a little odd, but I really appreciate that it is based on a well-document standard (Commonmark) as well as used by GitHub. Thank you.

I have changed my opinion and think this works as designed.
