### ISSUE TITLE
Installation on Raspberry Pi

### ISSUE THREAD

**Issue by morpheus-87** [codimd/server#145]
In the documentation about manual installation, there is the following passage: For building CodiMD we recommend to use a machine with at least 2GB RAM

What does building mean in that context?

I have a Raspberry Pi with just 1GB RAM and I would like to install CodiMd on it, is that possible?

**Comment by ccoenen** [comment]
If you do a manual setup, there's a step that compiles the frontend JavaScript. (`npm run build`) this does quite a lot of things and usually requires a lot of ram. If you can use docker images, you'll not have to do this part.
I did not try this myself, but you should also be able to build these files on any other computer, and then transfer them over to your pi.

**Comment by ccoenen** [comment]
If you have any further questions or if you need assistance with a setup, let me know. I'll close this here, but feel free to ask whatever you like. For a more interactive chat, you can also [join us on riot](https://riot.im/app/#/room/#codimd:matrix.org) or in our [community discourse](https://community.codimd.org/).

**Comment by morpheus-87** [comment]
Thank you very much for your fast answer! Wouldn't it be an idea to upload an archive including all dependencies and the built frontend JavaScript with every release?

**Comment by SISheogorath** [comment]
That's right. It just that we didn't find the time to do this yet. If you are familiar with Travis CI, it would be great if you would add such a step to the CI pipeline :)

**Comment by titulebolide** [comment]
Hey! I've just been through this issue and I succeeded to make all of this running on my RPi 4.
Here is the walkthrough:
Install the .deb package from `wget https://github.com/fg2it/phantomjs-on-raspberry/releases/download/v2.1.1-wheezy-jessie-armv6/phantomjs_2.1.1_armhf.deb` (with dpkg or gdebi) (you might need to install beforehand the following packages : `ttf-mscorefonts-installer
libfreetype6 fontconfig-config fonts-dejavu-core libexpat1
fontconfig-config fonts-dejavu-core libexpat1 libfontconfig1 libfreetype6`)
Then to make it work you probably need to set this : 
```export OPENSSL_CONF=/etc/ssl/```
Once this is done you will be able to run
```bin/setup```
Just note that yarn should be up to date :wink: because I used the native one which didn't knew what to do with the option --pure-lockfile
