### ISSUE TITLE
Support for R markdown

### ISSUE THREAD

**Issue by yusf** [codimd/server#149]
There's this thing called rmarkdown which renders charts out of R code:

> R Markdown is a file format for making dynamic documents with R. An R Markdown document is written in markdown (an easy-to-write plain text format) and contains chunks of embedded R code
— [source](https://rmarkdown.rstudio.com/articles_intro.html)

I think it would be interesting to have inside CodiMD if possible.

**Comment by zeigerpuppy** [comment]
Supporting R Markdown would be really cool, but there's a lot of complexity involved in doing this. The main complexity is that R-Markdown is deigned to also designed to run through a pandoc engine before producing the final output.
 A first step may be more achievable, supporting R code snippets by sending them to an R parser. 
incidentally l, if you're interested in seeing a combination of real-time editor with R-Markdown, the open source product [Cocalc](https://cocalc.com) does that.  The editor in CoCalc is not as sophisicated as CodiMD but it does show the sort of environment you need to manage R properly.  In fact, a more productive plan would probably be to integrate the CodiMD editor into CoCalc rather than try to rebuild R-Markdown support in to CodiMD!

**Comment by davidmehren** [comment]
As [CoCalc](https://github.com/sagemathinc/cocalc) already supports R Markdown and integrating the R Markdown pipeline into CodiMD seems to be *very hard* I'm going to close this for now. If anyone still want's to take a stab at this, please feel free.

**Comment by zeigerpuppy** [comment]
There may be a poor man's way of using the codimd editor for RMarkdown.
The benefits of this approach would be to bring multi-user, real-time editing to RStudio

Example: 
- RStudio domain: https://r.example.net
- CodiMD domain: https://codimd.example.net

1. install an RStudio Server (open source)

2. set up cross site permissions

  ```apache
  Header set Content-Security-Policy: "frame-ancestors 'self' https://r.example.net"
  ```

3. create an R project to display editor and pull markdown from CodiMD

   ```r
   setwd("~/R Projects/RMarkdown_Test/")

   # load CodiMD into the viewer   
   # more info on the viewer here: https://support.rstudio.com/hc/en-us/articles/202133558-Extending-RStudio-with-the-Viewer-Pane
   viewer <- getOption("viewer")
   viewer("https://codimd.example.net/RMarkdown_Test?both") 

   # Download working file from hackmd and save the file locally
   download.file(url='https://codimd.example.net/RMarkdown_Test/download', method='wget', destfile='RMarkdown_Test.Rmd' )
   
   # - now process your R-markdown however you like in RStudio
   ```

![rst](https://user-images.githubusercontent.com/415981/88494193-32d6d300-cff8-11ea-9130-d9b9aa52dd34.png)
