### ISSUE TITLE
Community Call! (subscribe here to get notified)

### ISSUE THREAD

**Issue by ccoenen** [codimd/server#16]
The probably most important aspect of an open source project is the community. This is why we try to have semi-regular community calls. We use a tele-conferencing software (usually jitsi) for this. It is one more way to keep in in touch and to make your voice heard.

Usually we schedule these on the first sunday of a month at 18:00 UTC, but this is not set in stone.

If you wish to be notified, please subscribe yourself to this issue. We will add new appointments here and you'll get an email when we do.

**Comment by ccoenen** [comment]
Next community call: [07.04.2019 18:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=4&day=7&hour=18&min=0&sec=0&p1=83&p2=241&p3=224)!
Collect topics in this document: https://demo.codimd.org/TZd9zd6fT9il505uKjCICQ
Meeting will be held via Jitsi: https://meet.jit.si/CodiMD

**Comment by SISheogorath** [comment]
Since our community forum is up and running, we moved this topic there:

https://community.codimd.org/t/codimd-community-call/19

You can subscribe by creating an account in the forum or using an RSS reader. Whatever you prefer :)

We would definitely prefer some members there, so go ahead and join us! :wink:
