### ISSUE TITLE
1.5.0 Alpine

### ISSUE THREAD

**Issue by dargmuesli** [codimd/server#164]
Hey there,
where is the CodiMD Docker image v1.5.0 **alpine**? I can't find it 😮

**Comment by SISheogorath** [comment]
Hey, I had some issues building it on release but since I'm traveling since then, I didn't have the time to figure out why it's currently failing. Therefore I hope you are fine when I look into those things next week when I'm back home and going through all things that I missed.

Of course, you are also welcome to look into the build and why it failed:

https://travis-ci.org/codimd/container/jobs/572492244

Sorry for the inconvenience, but I'm sure we can figure it out 👍🏻

**Comment by dargmuesli** [comment]
Ah ok, no problem. Quickly looking at it, it seems like a network issue. Might be temporary? Maybe just try a build restart for now. Otherwise, happy travel :)

**Comment by dargmuesli** [comment]
I just noticed that I should've raised the issue at codimd/container...

I had a more detailed look at the errors and saw that the issue occurs not only on alpine builds. First of all, this line makes me feel slightly uncomfortable:
https://github.com/codimd/container/blob/2f5909aed675fb4986f920fa478c154bf721de1a/tests/newNote.sh#L23
What's the reason to use `sleep` as an uptime check? But the reason for those seemingly random build fails is most likely something else and probably related to changes in this repo.

**Comment by SISheogorath** [comment]
The basic idea is to create a new note and check if the container survives this. It's a very rough test and can of course fail for not exactly the reason stated in the test, but at least there is some feedback.

**Comment by dargmuesli** [comment]
Looking at https://travis-ci.org/codimd/container/jobs/578282692 it seems that it doesn't matter which test runs as the `Default test`is failing there. Must be a different issue.

**Comment by dargmuesli** [comment]
I ran the tests locally and no issues occurred.

**Comment by SISheogorath** [comment]
Mhm, that makes things even worse.

I hope I find the time to look into this tomorrow. Might takes a few days more, have to catch up on some stuff.
