### ISSUE TITLE
Editor: Toolbar is dark in day mode

### ISSUE THREAD

**Issue by HerHde** [codimd/server#23]
![dark toolbar](https://user-images.githubusercontent.com/7630662/55442666-87ef0a00-55a7-11e9-9aef-68e7a461d629.png)

The toolbar stays dark if the editor is changed to day mode.
I would expect it to turn light as well.

**Comment by ccoenen** [comment]
at the same time, the upload button does not honor night mode:

![grafik](https://user-images.githubusercontent.com/124909/55511156-32c2ff00-5660-11e9-8f6c-84904ed1a6eb.png)

**Comment by SISheogorath** [comment]
:sweat_smile: Who didn't take care of that? I'll provide a PR to fix both :)

**Comment by HerHde** [comment]
Oh, and the label changes to the last chosen file's name. Not sure whether this is intended, but I guess it's due to the `<input type="file">`.
And you get no response if the chosen file type is not supported.

**Comment by SISheogorath** [comment]
Some hints for implementation:

In order to fix the light mode for the toolbar, there will be the need of manipulating the classes of the toolbar element using this function:
https://github.com/codimd/server/blob/36c083277e6c74bb6eac495971522e6932cfc207/public/js/lib/editor/index.js#L414-L447

The color difference between the upload button and the rest comes from this class:

https://github.com/codimd/server/blob/36c083277e6c74bb6eac495971522e6932cfc207/public/css/index.css#L14-L17

Finally the toolbar itself can be found here: https://github.com/codimd/server/blob/master/public/js/lib/editor/toolbar.html

If any further help is needed, feel free to reach out :)

**Comment by ccoenen** [comment]
Most of this ticket has been fixed in #44, and I created #63 to address the upload button at a later time.
