### ISSUE TITLE
Emoji's auto-completion is not available in the ![link-alt context]()

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [codimd/server#233]
Refer the following reproduction clip:

![CodiMD emoji auto-completion issue reproduction clip](https://user-images.githubusercontent.com/13408130/70409945-6a543780-1a88-11ea-9b1d-714c1a2120d1.gif)

The auto-completion is not available while create/editing links, which is a valid use case.

**Comment by ccoenen** [comment]
more general: it does not work if anything is following on the same line.

![emoji-autocomplete](https://user-images.githubusercontent.com/124909/70419006-e3da2e80-1a64-11ea-8486-e8db6ac8848e.gif)

**Comment by Lin-Buo-Ren** [comment]
> more general: it does not work if anything is following on the same line.
> 

Good catch, however I'm not exactly agree with that notion as the issue occurs at my first attempt on the line.

**Comment by ccoenen** [comment]
yes, but as soon as you type `[` the matching closing bracket `]` appears behind your cursor, so I think it's the more general case that applies here, too.

And it's definitely something we should fix.

**Comment by SISheogorath** [comment]
Just as hint: The autocomplete currently only works at the end of the line. If there is a character behind that, it currently won't work.

**Comment by Lin-Buo-Ren** [comment]
Feel free to improve the issue title if it's isn't a duplicate.

**Comment by bluehood** [comment]
Hi, I might (or might not, no promises) have some time to look into this. Could you point me to the relevant area of the codebase? :)

**Comment by SISheogorath** [comment]
Sorry for being late with this, here you go:

https://github.com/codimd/server/blob/313eb74ed697c5260df9293b1aefe3695cf65a5a/public/js/index.js#L3107

Hidden in the probably biggest mess in our code base :X organizing this is going to be a big project.

**Comment by ErikMichelson** [comment]
I had some ideas of how to maybe fix that, but they didn't work. Why? Because we use an old version of the jquery-textcomplete library. I looked for the newest version, but the library isn't maintained anymore. The author suggests to use [textcomplete](https://github.com/yuku/textcomplete) instead. There does exist an [editor-plugin for CodeMirror](https://github.com/yuku/textcomplete.codemirror) and both library and plugin are deployed via npm.

Instead of investing time for fixing our implementation with the old library, I suggest switching to the newer library.

**Comment by ErikMichelson** [comment]
This problem won't exist in the [new frontend for 2.0](https://github.com/codimd/react-client) anymore.
