### ISSUE TITLE
Zero Knowledge storage backend

### ISSUE THREAD

**Issue by davidak** [codimd/server#241]
CodiMD seems very similar to [CryptPad](https://cryptpad.fr/).

CodiMD uses Markdown and has a very intuitive editor and CryptPad (like the name suggests) encrypts the data in the client.

Have you considered collaborating with them and/or implementing a Zero Knowledge storage backend?

This would be a great feature to improve privacy when storing private data on a public instance. (You still have to trust them actually using this software without backdoors)

**Comment by bluehood** [comment]
Hi,
not a codimd developer, but I'm interested in understanding the usecase:

* if I'm using a CryptPad instance that is hosted by a third party, don't I have to trust them (blindly) on the fact that they will encrypt my text before storing it?
* if I'm self-hosting a CryptPad/CodiMD instance, would you say there is still an advantage in encrypting things on disk?

**Comment by ccoenen** [comment]
It has been discussed before we parted ways with the hackmd organization. The old discussion was here: https://github.com/hackmdio/codimd/issues/138

(just posting this just for reference, I'm not categorically against this, but a user would need to have some way of ensuring that the CodiMD installation has not been tampered with. If there is no such guarantee, this feature is meaningless.)

**Comment by SISheogorath** [comment]
Before we go into this, I think the big step would be to separate backend and frontend here. Obviously for the already pointed out reasons.

Also we need to notice that right now the CodiMD server is not just a coordinator but an equal member of the conversation between the clients and therefore talks generates the same state as they do due to awareness of the content. If we want to encrypt content, this means it'll fundamentally change how CodiMD handles clients. Not that this wouldn't be a good idea, but it simply is a huge change in the CodiMD that one shouldn't underestimate.

**Comment by bluehood** [comment]
Would client-client communication have to be a thing? So they can exchange private keys without telling the server.

**Comment by davidmehren** [comment]
Sorry everyone, but I am going to close this issue. With the current and future architecture, the server always has the (clear-text) state of the document in RAM. Changing this or adding some kind of encryption layer might be technically possible, but I would guesstimate the chance of that happening in the next few years as very close to zero, especially as there is already an established zero-knowledge editor.

If *you* are interested in contributing such a feature after 2.0 is released, please reopen this issue or talk to us in the community chat.

**Comment by haslersn** [comment]
One use case for this feature is to make sure that somebody who steals/seizes the server cannot read the contents of notes. (See: https://blog.fefe.de/?ts=9c4b7595)

For this use case, it would be ok if the clear-text state of the document is stored in RAM while editing. It just needs to be stored encrypted in the database and the key mustn't be stored on the server, i.e. the key must be a part of the URL. Ideally the key is stored in the fragment and sent to the server via JavaScript, so that it doesn't appear in any logs.
