### ISSUE TITLE
wishlist: when opening the login form, the username field should be focused

### ISSUE THREAD

**Issue by hydrargyrum** [codimd/server#249]
When I click the "sign in" button, the login form pops up, but unlike in many login forms ([github's](https://github.com/login) for example), no input field is focused, so I can't type my login/password straight away, I have to click on the username field and then I can type.

Of course, it's minor, it's a little detail, but I bet many users will appreciate it!

**Comment by ErikMichelson** [comment]
The question is: Which login field should be focused when there are multiple ones (like email login and LDAP login)? Should all user-name fields (email, ldap, openid) get an `autofocus` attribute?

**Comment by hydrargyrum** [comment]
The simplest implementation would be to take the first one. Else, would need to define what would be the "most probable" field (if you have an LDAP, it's likely you prefer users logging via LDAP?).

**Comment by ErikMichelson** [comment]
I've just seen this is not as easy as just adding the autofocus attribute because of the modal dialog. I'm investigating if there is any solution. My suggested "ranking" would be like LDAP -> email -> OpenID.

**Comment by ccoenen** [comment]
having focus on any of them is better than what we currently have, so I'd say it's a win. I don't have any objections to your ranking, either.

**Comment by SISheogorath** [comment]
Personally I think the better plan is to move the login to an own page
`/login` for example. This would allow automatic redirects when just
one SSO provider is available as well as additional hardening towards
minimized use of JS and CSS (maybe even hardened CSP).

It would mean an additional round-trip to get the login done, but the
flexibility we would achieve by doing this, should be worth it.

Otherwise also no objections form my side about the priorities.

-- 
Signed
Sheogorath

OpenPGP: https://shivering-isles.com/openpgp/0xFCB98C2A3EC6F601.txt

**Comment by ErikMichelson** [comment]
Generally I agree with you, @SISheogorath. An own login page would fit nicely to the idea of a "my account"-page. But getting that done before 1.6.0 release sounds quite visionary. Therefore, I suggest to just fix this (as in #250) to have at least a little better UX.
