### ISSUE TITLE
feature resquest: SEO and MetaTag

### ISSUE THREAD

**Issue by JOduMonT** [codimd/server#285]
Hi;
I saw few note about SEO in the [Release Notes](https://demo.codimd.org/s/release-notes#)
but don't see any mention in the Documentation or in the Forum
It is possible to develop about this ?

**Comment by SISheogorath** [comment]
When you mean the OpenGraph metadata, here you go: https://demo.codimd.org/yaml-metadata#opengraph

But for similar questions, I would ask you kindly to use the [forum's support category](https://community.codimd.org/c/support) instead as the question is probably useful for a broader audience.

If this is an actual feature request, then I kind of miss out, what is actually requested. SEO is a broad topic and it would be great that, given it's a feature request and not a support question, you could enrich the topic with an example or some documentation or definition of what you are referring to. Otherwise it's hard to understand what you expect to be added to CodiMD and the feature request will probably never be implemented as no one really knows what you meant.

**Comment by JOduMonT** [comment]
DONE: https://community.codimd.org/t/how-to-use-seo/84
