### ISSUE TITLE
Console: DevTools failed to load SourceMap mermaid.min.js.map

### ISSUE THREAD

**Issue by zhangyoufu** [codimd/server#289]
Chrome Console: `DevTools failed to load SourceMap: Could not parse content for https://example.com/s/mermaid.min.js.map: Unexpected token < in JSON at position 0`

Found `//# sourceMappingURL=mermaid.min.js.map` in `build/pretty-pack.ae39eb940275f427573c.js`

**Comment by mrdrogdrog** [comment]
The webpack config uses the script-loader to include `mermaid.min.js`. This file includes a reference to a source map, that is neither copied or processed, because the script loader just dumps the file content into the build. Also we don't create source maps for the production build.

TL;DR: Nothing to fix here, as we don't use source maps in production build.
