### ISSUE TITLE
Can CodiMD Be Horizontally Scaled?

### ISSUE THREAD

**Issue by zicklag** [codimd/server#292]
Hey there, I was curious, is it possible to horizontally scale CodiMD across multiple servers, behind a load balancer, with the same database for each instance, and still maintain the realtime editing capability?

**Comment by SISheogorath** [comment]
No. I did some experiments with this and wrote a custom proxy to run in front of multiple instances that would take care of the sessions and make sure everyone ends up on the same server when trying to access the same note.

Main problem: Application caching. We run sequlize as ORM and also write back history only every once in a while in order to reduce the amount of "diffs". Therefore the nodejs application is not stateless.

But looking at the demo instance with around 70 parallel active users in average and more than 20000 notes. It's reasonable to say that the resource usage is small enough that you don't need to scale horizontally. If you want HA, setup some kind of container orchestration and make sure your database appears on the other side if you ever have to let an instance pop up at the other end of the room. Otherwise a regular update takes a few seconds, you users will survive this ;)

Keep it simple: https://www.gkogan.co/blog/simple-systems/ (Nice article about complexity I came across a few hours ago)

**Comment by zicklag** [comment]
OK, cool. Thanks for the swift response! :smiley:

**Comment by oupala** [comment]
In the end, horizontal scaling would require multiple instance of codimd, each of these instances having its own database. There would be no state to share.

The loadbalancer would randomly redirect user to a different instance. The note would have a specific url (ie. https://instance3.mycodimdpool.example.org/) and all users would connect on this url.

The drawback of this solution is that a user would have notes distributed over all the instances.

**Comment by oupala** [comment]
@SISheogorath Can you explain a bit more how wold you achieve HA?

**Comment by zicklag** [comment]
Here's an idea, without knowing exactly how CodiMD is currently architected:

To scale your database, you just use the techniques that PostgreSQL already provides to scale their database. That handles that data storage and persistence HA. Then you also need to run multiple instances of CodiMD and point them all to the same database. Then you just need to handle the real-time event layer, which you could do with a message Queue like [RabbitMQ](https://github.com/rabbitmq/rabbitmq-server), maybe.

I'm not sure how worth it that effort is, but I *think* it would work.

**Comment by SISheogorath** [comment]
@zicklag No need for rabbitMQ. Just make sure that the same URL terminates on the same CodiMD instance and you are fine. E.g. `https://demo.codimd.org/features` would always hit instance A while `https://demo.codimd.org/release-notes` would route all users to instance B.

That in combination with a synchronized data backend, and you would get horizontal scaling without changing a single line of Code in CodiMD. 

@oupala For practical reasons I simply recommend to solve the HA situation on an orchestration layer. Means either you have a moveable VM that is managed by your virtualisation environment or you have a container orchestration like K8s which makes sure that the container comes back up again, when it was down.

I haven't seen a technical reason to implement horizontal scalability in CodiMD yet and I would like to avoid this complexity if possible.

**Comment by zicklag** [comment]
@SISheogorath Ah, yes, that's right. Well, if you could do horizontal scaling without changing CodiMD, then then somebody could make it a separate project if they needed it.

> E.g. https://demo.codimd.org/features would always hit instance A while https://demo.codimd.org/release-notes would route all users to instance B.

Actually, I'm pretty sure that is trivially implemented with [HAProxy](http://www.haproxy.org/) by telling it to route to the backend server based on the hash of the path. If we tried that out and it worked, it would leave the only thing for us to do is put a tutorial in the docs!

**Comment by oupala** [comment]
If multiple instance of codimd are using the same database, or the same cluster of replicated databases, where is stored the user history? The last edited notes?

If it is on the codimd side, a user will have one history per codimd instance. If this history is stored into the database, a user will have only one history, whatever codimd instance he is using.

To sum up, HA could be achieved by container orchestration (this is what we are doing). Horizontal scaling of the database could be achieved using a database replication process (depending on the database engine you're using). And finally, horizontal scaling of the codimd instance could be achieved by using a loadbalancer that is taking care of session affinity so that every user that want to edit the same note should be redirected to the same instance.

Nothing is managed on the codimd side, but this should be achieved on the architecture level of the solution.

My last question is then about the user history, as explained at the beginning of this comment.

**Comment by SISheogorath** [comment]
@oupala CodiMD itself is almost stateless in the sense that it doesn't store any data locally. You can do with your database whatever you like as long as CodiMD can contact it and do its queries it doesn't care.

Main problem with multiple CodiMD instances is: There will be cached objects in the JS runtime for the document and maybe even for content from the ORM. It's not intended to have more than one CodiMD instane running in parallel. But if you really want to try and have things eating your cat, you can go for it. There is, besides some cache invalidation issues, which I just mentioned, nothing that prevents you from running multiple instances.
