### ISSUE TITLE
I love CodiMD

### ISSUE THREAD

**Issue by lanefu** [codimd/server#295]
just a thank you.   CodiMD solved my forever problem of note-taking in a way that was portable, flexible, and easy.    

lane

**Comment by SISheogorath** [comment]
Thank you for your very warm words. It's great to hear that the project helps people in their daily routine. Every contributor to the project can be proud of the part the added to it. From a typo fix to rewriting or in general contributing large parts of the code base. You guys are awesome! :)

---

It might sounds a bit catchy, but since we don't run analytics or other telemetics it would be great if you would share your story and how you use CodiMD in [our Forum thread](https://community.codimd.org/t/how-do-you-use-codimd/18).

Of if you consider the way too far, over here would be of course also fine, in the forum it would just be more central 😉

**Comment by lanefu** [comment]
yep will post there! thanks
