### ISSUE TITLE
Strange Default Config File

### ISSUE THREAD

**Issue by titulebolide** [codimd/server#296]
Hello dear CodiMD team!

Since several hours I am going through the process of installing manually codimd on my server, and I encounter two details that I want to expose to you:

 - First off, the latest version of `hsts` (I have no idea what it is ^^) raise the following warning when using production server : ```hsts deprecated The "includeSubdomains" parameter is deprecated. Use "includeSubDomains" (with a capital D) instead. app.js:85:18``` It is not much, but you would maybe be happy to see it.

 - Second off, the `config.json.example` file contains has in line 21 : `"domain": "localhost"`. When running the default server with `npm start --production` this makes that every static file can't be found because the server is starting at `localhost:3000`. Maybe you would want to set `"domain": "localhost:3000"` as the default configuration?

Thanks for your work!

**Comment by SISheogorath** [comment]
Hi, thanks for the hints! We are currently working on version 2.0 which should fix the camelcase warning with HSTS and even more important: the quite confusing domain config.

I still recommend you to go ahead and install CodiMD 1.6.0 because 2.0 will still take a while to come out. Meanwhile when you have support questions, feel free to join [our community forum](https://community.CodiMD.org) and if you look for a cozy place with some Dev talk and other fun, check [our matrix room](https://riot.im/app/#/room/#codimd:matrix.org).

Looking forward to see you around :)
