### ISSUE TITLE
Comments appear in pdf export

### ISSUE THREAD

**Issue by SimonRassmann** [codimd/server#341]
Comments do not appear in the set markup document but do in the exported pdf

Example:
`<!-- This is a comment -->`
should yield an empty pdf export but gives
![comments_pdf](https://user-images.githubusercontent.com/54679484/80308300-7e49cd00-87ce-11ea-980c-e66160770b90.png)

**Comment by SISheogorath** [comment]
How do you do a PDF export if I might ask? We disabled that feature in version 1.5.0 and removed it in the upcoming 2.0 release.

**Comment by SimonRassmann** [comment]
We are not on a release but on the current master branch, where pdf export is still enabled by default.

Under these circumstances, this is not an important issue right now, but it would be nice to have if pdf export gets reintroduced in the future

**Comment by ErikMichelson** [comment]
May I ask, to which commit your instance is pointing (see source code link in the footer of the intro page)?
On the current master branch pdf export is disabled by default due to security problems. [Here](https://github.com/codimd/server/blob/master/lib/config/index.js#L192-L196) is the corresponding code snippet.

**Comment by HermannDppes** [comment]
We figured it out. It got lost in translation but we are/were running the [HackMD version](https://github.com/hackmdio/codimd).

PSA: If you have two projects that are named identically and neither mentions the mere existence of the other, it's not exactly easy to figure out that there might be another one.
