### ISSUE TITLE
some variables can be set using a configuration file, but not using an environment variable

### ISSUE THREAD

**Issue by oupala** [codimd/server#354]
Looking at the documentation, it appears that some variables can be set using a configuration file, but not using an environment variable.

This is the case for the variable `documentMaxLength` for example.

Is it a lack of documentation, or is there really some differences between configuration by a configuration file, of using some environment variables?

**Comment by SISheogorath** [comment]
This is an actual difference in the ability to configure things. It's intentional that some configs are not available as environment variable. Namely: All we consider to be set so rarely, that the one or two people who want to set them, can write an own config.json and put it in place. Each option we maintain in more than one place, comes with a cost, therefore the limitation in some cases.

**Comment by oupala** [comment]
So, the fact that `documentMaxLength` is not configurable by environment variables is intentional, right ?

I'm asking because we are regularly reaching this limit of 100.000 lines.

**Comment by oupala** [comment]
Another question is about the default value of `documentMaxLength`.

We find this too low for our usage.

What do you think of this?

**Comment by SISheogorath** [comment]
There is AFAIK no scientific background behind that number, but I definitely do not recommend to increase it drastically. The larger your notes are, the larger and faster the note history table grows and with that your storage needs. 100000 chars are a reasonable size for a document. But if you want/need more, than feel free and change it using your config.json :slightly_smiling_face:

**Comment by oupala** [comment]
We'll see with our users if they find that 100000 is ok or too low.
