### ISSUE TITLE
notes was hidden after upgrade from 1.5.0 to 1.6.0 

### ISSUE THREAD

**Issue by chenboshiun** [codimd/server#363]
Hello CodiMD Support:

As some of the user's notes was hidden, after upgrade from 1.5.0 to 1.6.0 

But, he can read / write it via note URL, if he remember note URL

notes seems are exist, just not show on note dashboard,

How can I resolve this problem?

Thanks. :)

**Comment by DerMolly** [comment]
Has the user an account on your instance or does he use it anonymously?

**Comment by chenboshiun** [comment]
No , he has a LDAP account, we disable anonymously config

**Comment by SISheogorath** [comment]
It reminds me of a case we had on the demo instance a few weeks ago:

https://github.com/codimd/server/issues/182

We were never really able to reproduce or debug this problem. The way it was resolved was that I figure out the account, created a list of all his notes, put that into a note that was set to "locked" and change the `ownerId` in the database to his user id before sending him the link.

They would need to reopen all notes manually, which is sure not a nice solution, but it's a problem that seems to appear very rarely in production and so far no one could provide steps to reproduce the issue :/

**Comment by chenboshiun** [comment]
hmm, OK

How to create a list of all user's notes and change the ownerId in the database to user id before sending him the link ?

Cloud you please show Standard Operation Proceduce or tutorial ?

Thanks :)

**Comment by SISheogorath** [comment]
There is no official guide for that, because it's not an intended behaviour. Depending on login method used by the user, you might need to adjust from profile to email or make your search pattern more specific but roughly this is the procedure:

1. Connect to the database
2. Get the userID from the database using the following query: `SELECT id FROM "Users" WHERE profile LIKE '%<username>%';` (replace `<username>` with the username)
3. Get all notes the user owns using the following query: `SELECT shortid FROM "Notes" WHERE "ownerId" = '<user id>';` (replace `<user id>` with the ID you got as output from the previous query)
4. Take the list and prepends all queries with the URL of your instance. (For the demo instance and an shortid like `abcdefg` it would result in `https://demo.codimd.org/abcdefg`)
5. Put this resulting list of links into a note of your account and set it to "Private" permission. If you press publish and copy the shortid (the part shown after `/s/`)
6. Update the note ownership based on it's shortid using the following query: `UPDATE "Notes" SET "ownerId"='<user id>' WHERE shortid='<shortid>'` (replace `<user id>` with the id from 2nd step and `<shortid>` with the shortid from step 5)
7. Send the link to the user who can just spam out ctrl + click on all notes to add them back to his note history.

The solution isn't great and as soon as there is a way to reproduce the issue, we'll fix it ASAP, but for now this should work and solve the problem.

**Comment by chenboshiun** [comment]
Hello @SISheogorath 

OK，I have followed your procedure, I Get all notes and send to user

Thank you for your help
