### ISSUE TITLE
Cursor motion past fold opens the fold

### ISSUE THREAD

**Issue by inducer** [codimd/server#380]
Steps to reproduce:

* Close a heading fold using the fold gutter (click on the downward caret).
* Move cursor to same line as the folded heading.
* Press "cursor down".

Desired behavior:
* Cursor moves past fold.

Observed behavior (d30e022c7f4c0b05e4f4424a35c771678baa477b):
* Fold opens, cursor on first line of previously folded-away text

Notably, the CodeMirror [folding demo](https://codemirror.net/demo/folding.html) (scroll to the bottom for the Markdown one) behaves correctly.

I'm wanting to add [keyboard shortcuts for folding](https://github.com/inducer/codimd-server/commit/81f7a1a5fc4ad02810a534c968ef030315abc54e) (and that works), but there's not really a point to submitting a PR for that until folds stay folded.

**Comment by inducer** [comment]
I should add that using the mouse to move the cursor to the next line works flawlessly.

**Comment by davidmehren** [comment]
I just tried this on demo.codimd.org in Firefox 79.0b6 and the folds stay closed when using the down arrow. If I use the 'arrow right' key to move the cursor from the end of a heading to the next character, the fold opens, but that seems to be intentional. Could you check if you experience the problem in the demo instance?

**Comment by inducer** [comment]
You're right, it works correctly on the demo instance right now. I'll investigate on my end. Thanks!
