### ISSUE TITLE
How to migrate user's note from LDAP to SAML

### ISSUE THREAD

**Issue by chenboshiun** [codimd/server#427]
Hello CodiMD Support:

We have two authentication method:

1. LDAP
2. SAML

Recently, We want to remove LDAP and change to SAML

But, existing user access CodiMD via LDAP,  All of user's notes on LDAP account

We want to migrate user notes from LDAP to SAML

I guess we need to migrate data on DB scheme

Could you please show CodMD Table Name to me If you can ?

or do you have recommendation method or procudure ?

Thank you

**Comment by SISheogorath** [comment]
There is neither an official documentation, nor have I ever done this myself.

But roughly it should work with the a patch **after** this lines in the SAML authentication provider:

https://github.com/codimd/server/blob/3cc957a88b3b434edbc9db072c7259d188333c9a/lib/web/auth/saml/index.js#L39-L44

The patch should roughly look like this:

```js
// migrate users from LDAP to SAML
  models.User.findOne({
    where: {
      profileid: `LDAP-${profile.username}`
    }
  }).then(function (user) {
    user.profileid = profile.id.toString()
  });
```

This is untested and should not directly be used in production without some previous, detailed testing. But looking at the problem, it's probably the easiest way without any additional manual work.

How to test it? Well, take a copy of your production database and config, fire up a new instance of CodiMD on it, add the patch, login using SAML to a previous LDAP account and cross your fingers :D

What does the patch do? It queries the account model as if the LDAP provider would do, updates the profile ID so it becomes the one from the SAML provider and then the SAML provider can automatically do its job as if the user always was SAML user.

Problems you might run into:
1. My code is buggy (Maybe I'm missing some important declaration)
2. People use a different username in ldap than they use in SAML
3. Your LDAP is setup properly and uses a UID instead of a classic username as account identifier

The login to create the LDAP ID looks like this:
https://github.com/codimd/server/blob/3cc957a88b3b434edbc9db072c7259d188333c9a/lib/web/auth/ldap/index.js#L25-L50

So you might need to make the needed id available through SAML and replace the username statement in my code.

Alternative, long/manual way:

1. Let users sign-in using SAML in order to create an account (but do not let them use this account)
2. find their two accounts in the database using `SELECT id, profileid FROM "Users" WHERE profile LIKE '%<username>%';` (obviously replace `<username>`)
3. Copy the id and profileid of the SAML account
4. Delete the SAML account using `DELETE FROM "Users" WHERE id='<id of saml account>';`
5. Replace replace the profileid of the LDAP account with the SAML account's profileid using `UPDATE "Users" SET "profileId"='<SAML account profileid>' WHERE id = '<LDAP account id>';`

What level of automation you want to/can run, is up to you, I hope that helps :)

**Comment by DerMolly** [comment]
@chenboshiun If you don't have any more problems / questions, would you mind closing this issue?
