### ISSUE TITLE
can add wysiwyg mode, like tui.editor

### ISSUE THREAD

**Issue by runner-mei** [codimd/server#470]
can add wysiwyg mode, like [tui.editor](https://github.com/nhn/tui.editor).

it is friendly for nonprofessional user.

**Comment by davidmehren** [comment]
Thanks for the suggestion!
Sadly, this is something we (at least for the foreseeable future) won't do. WYSIWYG-editing is not in the scope of this project and would require extensive changes to our editor. If you have other suggestions about how we could improve the usability for nonprofessional users, don't hesitate to open an issue in the [frontend repo](https://github.com/codimd/react-client)!

**Comment by SISheogorath** [comment]
Note we had those discussions (in the old repository) before and it's simply not possible to provide proper support for all features while maintaining multiple editors, as editors are one of the main sources for integration work.

**Comment by giplt** [comment]
I guess the problem lies mainly in all the plugins that won't be easy to support in a WYSIWYG fashion?
An elegant solution to this would be to support only WYSIWYG editing for the basic markdown (headings, boldface, italic, adding image) and offer a split solution for special features. I.e. show an **un**editable render of the special feature (math equation, flowchart or whatever) in the WYSIWYG mode, with an overlayed edit-button that will expose the raw markdown code, either by toggling between edit and view or though a split-screen solution like Hegdedoc does so nicely.
This would allow nonprofessional users to collaborate on (those parts of) documents that are straightforward text.
