### ISSUE TITLE
Provide pre-built archives to avoid requiring a "huge" amount of RAM for installation ?

### ISSUE THREAD

**Issue by alexAubin** [codimd/server#487]
Dear CodiMD devs,

thanks for your work on that epic tool !

CodiMD is available as a Yunohost app since a few months (c.f. https://github.com/YunoHost-Apps/codimd_ynh )

Nevertheless many people are unable to install the app because the `yarn build` step takes up to 3.5 GB of RAM (while the Yunohost project is typically used by people running Raspberry Pi or small (~2GB RAM) VPS running other apps)

Do you think it'd be conceivable to ship pre-built archives such that people with low-end hardware would be able to install CodiMD more easily ?

Cheers !

**Comment by SISheogorath** [comment]
Yes! And this is actually a widely requested thing. Currently the main thing missing is someone to write it.

https://github.com/codimd/server/issues/96

If you are interested in working on this the referenced issues has some good starting points. Otherwise I have to look what my time allows me to do but I guess we all agree that it makes sense to have those pre-built releases.

**Comment by ErikMichelson** [comment]
The question is where to provide these images? Zipped as attachments to the corresponding release?

**Comment by ErikMichelson** [comment]
Do we want to close this issue here and continue discussion over in #96?

**Comment by alexAubin** [comment]
(Yes feel free to close that issue if that's a duplicate, sorry I should have done some issue tracker research before creating that one :stuck_out_tongue_winking_eye: )
