### ISSUE TITLE
History entry deletion is easily mistaken for Note deletion

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [codimd/server#62]
Problem found by my colleague.

## Reproduce instructions
1. Create a new note on <https://demo.codimd.org> with the following content:

```markdown
# Note deletion test
```

2. Open a new tab and browse <https://demo.codimd.org>, in the "History" view, click the "Note deletion test" note's cross button on the top left corner and select "Yes, do it!" button in the note deletion prompt
3. Go back to the original tab and refresh the page.

## Expected behavior
The original note is no longer available as it is "deleted"

## Current behavior
The original note is still available with its content retained.

**Comment by SISheogorath** [comment]
@Lin-Buo-Ren This might be unintutive and we should fix that in the long term perspective, but in the history tab you only remove it from your history, it doesn't delete the note. We should consider to add a button there, one to remove from history, one to remove the not as well.

Background: The notes are added to history by visiting them, not all of them are owned by use, of course you can't delete notes you don't own and therefore wouldn't be able to delete it at all. In order to keep you in control over your history view, the deletion from history is independent from the deletion of notes. (and for history reasons as deletion notes came in after the whole history deletion code).

**Comment by Lin-Buo-Ren** [comment]
For UI perspective I would expect at least the delete prompt mention that this operation only applies to the history itself.

**Comment by SISheogorath** [comment]
"Do you really want to delete below history?" isn't great wording, but I think it already mentions it.

But I also agree that the UX is quite terrible when people don't get it in first place :)

**Comment by ErikMichelson** [comment]
This is already implemented in the new frontend as shown below:

![image](https://user-images.githubusercontent.com/52606896/87105365-07639280-c25b-11ea-8d6a-60e94e20a4ce.png)

See codimd/react-client#171 codimd/react-client#299
