### ISSUE TITLE
includeSubDomains from hsts config outputs warning

### ISSUE THREAD

**Issue by ccoenen** [codimd/server#74]
There's a few places where we use a different naming than our hsts library. People configuring via config.js will get a warning like this:

    hsts deprecated The "includeSubdomains" parameter is deprecated. Use "includeSubDomains" (with a capital D) instead. app.js:85:18

It comes from this line here:

https://github.com/codimd/server/blob/de669c7b93a69966cee119ffda0da8b78e83a55a/app.js#L87

We have to decide what we do about it in a more general sense, though: we have this capitalisation in our own configs as well. Do we change this to also have the capital `D`? Does anyone even use this configuration option to change the value from its default?

https://github.com/codimd/server/search?q=includeSubdomains&unscoped_q=includeSubdomains

**Comment by ccoenen** [comment]
this is not _yet_ really a bug. It is more like future-proofing ourselves. Still, we should get rid of that warning.

**Comment by SISheogorath** [comment]
I think we should really start to collect some configurations soon in order to figure out what features are "dead" as in "are never used and are therefore obsolete". I guess this is one of them. I would even argue that running CodiMD directly with exposing TLS is something that uncommon that we might want to deprecate those things.

**Comment by ndom91** [comment]
Ah sorry just saw there was an issue for this already. I just submitted a PR fixing this a few minutes ago.

**Comment by InnayTool** [comment]
PR for this is #99 and it is included in #214.
