### ISSUE TITLE
Export to pdf

### ISSUE THREAD

**Issue by AndiLeni** [codimd/server#89]
Hello,
I've seen some installations with the option to export as PDF, but it seems to be disabled in the official demo. 
What's the reason to have it disabled? Was this feature removed some time ago? 

Regards
Andi

**Comment by SISheogorath** [comment]
No, it's not removed. There is an option to disable it as it caused some issues from time to time.

On the Demo instance, we use a docker setup, running in read-only mode which had problems due to some dependency that crashed when moving the created pdf between mountpoints.

It's also disabled on all alpine based container image versions, because of a missing dependency which prevents us from using it there.

In general, in a less restrictive environment, this feature is still available and enabled :)

**Comment by SISheogorath** [comment]
@TheBolliwood PDF export was disabled due to a critical security issue. I provided some details here:

https://github.com/codimd/server/commit/c1789474020a6d668d616464cb2da5e90e123f65

Since I'm not seeing a way to fix this problem easily with the upcoming release, we might opt to drop it completely. With dropping the feature, I'm going to provide a more detailed write up about the problem.

**Comment by ccoenen** [comment]
It's also mentioned as second item in the release notes:
https://github.com/codimd/server/blob/master/public/docs/release-notes.md#-150--2019-08-15-0000

**Comment by supagas** [comment]
So its completely dropped now? :/ if yes, very Sad

**Comment by ccoenen** [comment]
Personally, I don't know enough about this, to make an informed decision. I don't know the nature of the security issue or what would be needed to have this feature, but safely.

I _am_ pretty sure that it can be re-introduced when it is safe to do so. If anyone can put in the work to make that happen, I'm pretty sure that this will get merged into the project. Re-Enabling support - right now - will require you to change a few lines of code. We haven't removed PDF completely, we [just disabled the config-item](https://github.com/codimd/server/commit/c1789474020a6d668d616464cb2da5e90e123f65). We don't want to make it _easy_ to enable, but if you know enough JavaScript to edit these lines, you will get PDF support back - **at your own risk**.

**Comment by ErikMichelson** [comment]
Another option is to use for instance Chrome and to "print" the published note as a PDF file.

**Comment by rmdes** [comment]
> Another option is to use for instance Chrome and to "print" the published note as a PDF file.

This is what I have been doing, I export to HTML, open it with Firefox/Chrome and print it as PDF
